export const SocketTopic = {
	CONNECT: "connect",
	DISCONNECT: "disconnect",
	// room topic
	ROOM_JOIN: "room:join",
	ROOM_LEAVE: "room:leave",
	ROOM_JOIN_RESPONSE: "room:join-response",
	ROOM_LEAVE_RESPONSE: "room:leave-response",
	// device topics
	DEVICE_LOCATION_LAST: "device-location:last",
	// capture topics
	MESSAGE: "message",
	DEVICES: "devices",
	DEVICE: "device",
	DEVICE_NEW: "device.new",
	DEVICE_REMOVE: "device.remove",
	DEVICE_TRACKS: "device.tracks",
	DEVICE_SETUP: "device.setup",
	DEVICE_STATE: "device.state",
	DEVICE_CONFIG: "device.config",
	DEVICE_LAST: "device.last",
	DEVICE_CLEARED: "device.cleared",
	DEVICE_TRACK_END: "device.track.end",
	DEVICE_UNSUBSCRIBE: "device.unsubscribe",
	DEVICE_UNSUBSCRIBE_ALL: "device.unsubscribe.all",
	DEVICE_SUBSCRIBE: "device.subscribe",
	// bot control topics
	BOT_GET_IS_RUNNING: "bot:get:is-running",
	BOT_IS_RUNNING: "bot:is-running",
	BOT_REQ_STOP: "bot:req-stop",
	BOT_REQ_STOP_RESPONSE: "bot:req-stop:response",
	BOT_REQ_START: "bot:req-start",
	BOT_REQ_START_RESPONSE: "bot:req-start:response",
	// gps tracking topics
	ROOM_JOIN_REQUEST_GPS: "room:join:request",
	ROOM_JOIN_RESPONSE_GPS: "room:join:response",
	ROOM_LEAVE_REQUEST_GPS: "room:leave:request",
	ROOM_LEAVE_RESPONSE_GPS: "room:leave:response",
	ROOM_LIST_REQUEST_GPS: "room:list:request",
	ROOM_LIST_RESPONSE_GPS: "room:list:response",
	// VEHICLE TOPICS
	VEHICLE_SORTBY_GEOFENCE_RESPONSE: "vehicle:sortby:geofence:response",
	VEHICLE_SORTBY_GROUP_RESPONSE: "vehicle:sortby:group:response",
	VEHICLE_SORTBY_GEOFENCE_REQUEST: "vehicle:sortby:geofence:request",
	VEHICLE_SORTBY_GROUP_REQUEST: "vehicle:sortby:group:request",
} as const;
